import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));
await page.goto("http://localhost:3000/new", { waitUntil: "networkidle" });
await page.screenshot({ path: "../../.impeccable/review/new-empty.png" });
await page.click("text=Load the sample script");
await page.waitForTimeout(400);
await page.screenshot({ path: "../../.impeccable/review/new-filled.png" });
await page.click("text=Predict the drop");
await page.waitForTimeout(1300);
await page.screenshot({ path: "../../.impeccable/review/new-progress.png" });
await page.waitForURL(/\/a\//, { timeout: 15000 });
await page.waitForTimeout(2500);
await page.screenshot({ path: "../../.impeccable/review/new-result.png" });
console.log("landed on", page.url());
if (errors.length) console.log("ERRORS", errors);
await browser.close();
